name: Build and publish Docker Images

# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "images/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "images/**"
  workflow_dispatch:

jobs:
  setup:
    name: Setup build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Retrieve Docker tags
        id: set-matrix
        run: |
          echo "matrix=$(find . -name 'Dockerfile.*' -print | jq -cnR '{tag: [inputs | split(".")[-1]]}')" >> $GITHUB_OUTPUT

  build-push:
    name: Build and publish Docker Images
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Get refs - this will be used as tags later on
        shell: bash
        run: |
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
        id: get-refs

      - name: Set up Docker Context for Buildx
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/
          file: images/Dockerfile.${{ matrix.tag }}
          tags: |
            rpersee/john:${{ matrix.tag }}-${{ steps.get-refs.outputs.sha8 }}, rpersee/john:${{ matrix.tag }}
          push: true
